# fly.toml app configuration file generated for sinnau-com on 2026-07-04T11:34:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sinnau-com-production'
primary_region = 'sin'

[build]

[env]
NODE_ENV = "production"
ENVIRONMENT = "production"
BETTER_AUTH_URL = "https://sinnau.com"
PORT = "11085"
BODY_SIZE_LIMIT = "50M"

[[mounts]]
source = 'data'
destination = '/app/data'

[http_service]
internal_port = 11085
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
