export const AFFILIATE_ID_PREFIX = "aff";
export const AFFILIATE_APPLICATION_ID_PREFIX = "afa";
export const AFFILIATE_COMMISSION_ID_PREFIX = "afc";
export const AFFILIATE_PAYOUT_ID_PREFIX = "afp";
export const AFFILIATE_SUBSCRIPTION_EVENT_ID_PREFIX = "afs";

export const AFFILIATE_COMMISSION_STATUSES = [
  "PENDING",
  "PAID",
  "VOID",
] as const;

export const AFFILIATE_COOKIE_NAME = "affiliate_ref";
// 30 days
export const AFFILIATE_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 30;

export const AFFILIATE_SLUG_MAX_RETRIES = 5;

export const AFFILIATE_COMMISSION_RATE = 0.35;

export const AFFILIATE_APPLICATION_STATUSES = [
  "PENDING",
  "ACCEPTED",
  "REJECTED",
] as const;

export const AFFILIATE_APPLICATION_STATUS_LABEL: Record<
  (typeof AFFILIATE_APPLICATION_STATUSES)[number],
  string
> = {
  ACCEPTED: "Accepted",
  PENDING: "Pending",
  REJECTED: "Rejected",
};

export const AFFILIATE_ADVANTAGE_MIN_LENGTH = 10;
export const AFFILIATE_ADVANTAGE_MAX_LENGTH = 1000;
export const AFFILIATE_HANDLE_MAX_LENGTH = 255;

export const AFFILIATE_PAYOUT_ACCOUNT_ID_PREFIX = "afpa";

export const AFFILIATE_PAYOUT_METHODS = ["GOPAY", "BANK"] as const;

export const AFFILIATE_ACCOUNT_NUMBER_MIN_LENGTH = 5;
export const AFFILIATE_ACCOUNT_NUMBER_MAX_LENGTH = 30;
export const AFFILIATE_BANK_NAME_MAX_LENGTH = 100;
export const AFFILIATE_ACCOUNT_HOLDER_MIN_LENGTH = 3;
export const AFFILIATE_ACCOUNT_HOLDER_MAX_LENGTH = 255;

export const AFFILIATE_ID_FIELD_MAX_LENGTH = 255;
export const AFFILIATE_TEXT_FIELD_MAX_LENGTH = 500;
