export const CHAPTER_TITLE_MIN_LENGTH = 5;
export const CHAPTER_TITLE_MAX_LENGTH = 50;
export const CHAPTER_DESCRIPTION_MAX_LENGTH = 1000;

export const CHAPTER_SLUG_MAX_RETRIES = 5;
export const CHAPTER_SLUG_RANDOM_LENGTH = 6;
export const CHAPTER_SLUG_SHORT_RANDOM_LENGTH = 12;
export const CHAPTER_SLUG_MIN_SANITIZED_LENGTH = 5;
