export const STUDY_SET_TITLE_MIN_LENGTH = 5;
export const STUDY_SET_TITLE_MAX_LENGTH = 50;
export const STUDY_SET_DESCRIPTION_MAX_LENGTH = 2000;
export const STUDY_SET_FILES_MAX_COUNT = 32;
export const STUDY_SET_FILENAME_MAX_LENGTH = 255;

export const STUDY_SET_PAGE_LIMIT = 10;

export const STUDY_SET_VISIT_TTL_DAYS = 90;
export const STUDY_SET_VISIT_TTL_MS = STUDY_SET_VISIT_TTL_DAYS * 24 * 60 * 60 * 1000;

export const STUDY_SET_VISIBILITIES = ['PUBLIC', 'PRIVATE'] as const;
export const STUDY_SET_DEFAULT_VISIBILITY = 'PUBLIC' as const;

export const STUDY_SET_SLUG_MAX_RETRIES = 5;
export const STUDY_SET_SLUG_RANDOM_LENGTH = 6;
export const STUDY_SET_SLUG_SHORT_RANDOM_LENGTH = 12;
export const STUDY_SET_SLUG_MIN_SANITIZED_LENGTH = 5;
